import "_docs/views/CustomClasses/Animation.js"
import "_docs/views/CustomClasses/BackgroundColor.js"
import "_docs/views/CustomClasses/BackgroundPosition.js"
import "_docs/views/CustomClasses/BackgroundSize.js"
import "_docs/views/CustomClasses/BorderColor.js"
import "_docs/views/CustomClasses/BorderRadius.js"
import "_docs/views/CustomClasses/FontSize.js"
import "_docs/views/CustomClasses/Height.js"
import "_docs/views/CustomClasses/Inset.js"
import "_docs/views/CustomClasses/Keyframes.js"
import "_docs/views/CustomClasses/LetterSpacing.js"
import "_docs/views/CustomClasses/LineHeight.js"
import "_docs/views/CustomClasses/MaxHeight.js"
import "_docs/views/CustomClasses/MaxWidth.js"
import "_docs/views/CustomClasses/MinHeight.js"
import "_docs/views/CustomClasses/MinWidth.js"
import "_docs/views/CustomClasses/Opacity.js"
import "_docs/views/CustomClasses/Plugins.js"
import "_docs/views/CustomClasses/Screens.js"
import "_docs/views/CustomClasses/Spacing.js"
import "_docs/views/CustomClasses/TextColor.js"
import "_docs/views/CustomClasses/Translate.js"
import "_docs/views/CustomClasses/Width.js"
import "_docs/views/CustomClasses/ZIndex.js"
import "react"
import Animation
import BackgroundColor
import BackgroundPosition
import BackgroundSize
import BorderColor
import BorderRadius
import FontSize
import Height
import Inset
import Keyframes
import LetterSpacing
import LineHeight
import MaxHeight
import MaxWidth
import MinHeight
import MinWidth
import Opacity
import Plugins
import React
import Screens
import Spacing
import TextColor
import Translate
import Width
import ZIndex

export default function CustomClasses() {
  return (
    <>
      <Animation />
      <BackgroundColor />
      <BackgroundPosition />
      <BackgroundSize />
      <BorderColor />
      <BorderRadius />
      <FontSize />
      <Height />
      <Inset />
      <Keyframes />
      <LetterSpacing />
      <LineHeight />
      <MaxHeight />
      <MaxWidth />
      <MinHeight />
      <MinWidth />
      <Opacity />
      <Plugins />
      <Screens />
      <Spacing />
      <TextColor />
      <Translate />
      <Width />
      <ZIndex />
    </>
  );
}
