version: "3.7"

services:
    swag:
      image: ghcr.io/linuxserver/swag
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=crometool.duckdns.org
        - SUBDOMAINS=www,
        - VALIDATION=duckdns
        - DUCKDNSTOKEN=40ec2401-1546-484c-a2cd-26691ecc0ebb
        - EMAIL=ashdiashdiijsdjsid2827839aiwjdiwd@gmail.com
      volumes:
        - ~/docker_crome/config/swag:/config
        - ~/docker_crome/build:/config/www
      ports:
        - 443:443
        - 80:80
      restart: unless-stopped

    backend:
      build:  ./backend
      container_name: crome_backend
      ports:
        - "80:5000"
      command: -w

    frontend:
      build:  ./frontend
      container_name: crome_frontend
      volumes:
        - ~/docker_crome/build:/home/crome/web/frontend/build
      ports:
        - 5000
      depends_on:
        - backend
