version: "3"
services:
  backend:
    build: .
    restart: always
    container_name: backend
    volumes:
      - ./src/frontend/build:/home/crome-web/src/frontend/build
      - ../cert.pem:/home/cert.pem
      - ../privkey.pem:/home/privkey.pem
    expose:
      - 5000
    ports:
      - 5000:5000
      - 443:5000
      - 80:50000
    command: -s
