channels:
- default
- conda-forge
dependencies:
- aenum
- dill
- docker-py
- eventlet
- flask
- flask-socketio
- matplotlib
- pdm
- pip
- pre-commit
- pydantic
- pydot
- pygraphviz
- python-igraph
- python=3.10
- spot
- tabulate
- treelib
- pip:
  - bloom-filter
  - pyeda
name: crome-web
